name: Criar EXE da Capivara

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  criar-exe:
    runs-on: windows-latest

    steps:
      - name: Baixar o projeto
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar PyInstaller
        run: python -m pip install pyinstaller

      - name: Criar executável
        run: python -m PyInstaller --onefile --windowed --name MinhaCapivara main.py

      - name: Disponibilizar o EXE
        uses: actions/upload-artifact@v4
        with:
          name: MinhaCapivara
          path: dist/MinhaCapivara.exe


